service: invest-valid-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  memorySize: 128
  timeout: 300
  endpointType: regional

plugins:
  - serverless-mocha-plugin
  - serverless-offline
  - serverless-domain-manager

custom:
  allowedHeaders: 
    - Accept 
    - Content-Type 
    - Content-Length 
    - Authorization 
    - X-Amz-Date 
    - X-Api-key 
    - X-Amz-Security-Token 
    - X-Amz-User-Agent 

  customDomain:
    domainName: api.investvalid.com
    basePath: 'v1'
    stage: prod
    certificateName: investvalid.com
    createRoute53Record: true

functions:
  updateAvatar:
    handler: UserAttr/UpdateAvatar.update
    events: 
      - http:
          path: userAttr/updateAvatar
          method: post
          cors:
            origin: '*' 
            headers: ${self:custom.allowedHeaders}

