service: invest-valid-serverless

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: ap-southeast-1
  memorySize: 128
  timeout: 5
  endpointType: regionsl

functions:
  hello:
    handler: handler.hello

