service: invest-valid-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  memorySize: 128
  timeout: 60
  endpointType: regional

plugins:
  - serverless-mocha-plugin
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.investvalid.com
    basePath: 'v1'
    stage: prod
    certificateName: investvalid.com
    createRoute53Record: true

functions:
  updateAvatar:
    handler: UserAttr/updateAvatar.update
    events: 
      - http:
          path: userAttr/updateAvatar
          method: post
          cors: true

